name: Dependency Vulnerability Check

on:
  pull_request:
    paths:
      - '**/Gemfile.lock'
      - '**/package-lock.json'
      - '**/yarn.lock'
      - '**/pnpm-lock.yaml'

jobs:
  vulnerability-check:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1 # Specify the Ruby Docker image and version (you can use any Ruby version)

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Bundler
      run: gem install bundler

    - name: Run Trivy on base commit
      id: trivy-base
      run: |
        git checkout origin/main
        trivy fs --quiet --scanners vuln --pkg-types library -s HIGH,CRITICAL --format json . > base_vulnerabilities.json

    - name: Run Trivy on head commit
      id: trivy-head
      run: |
        git checkout FETCH_HEAD
        trivy fs --quiet --scanners vuln --pkg-types library -s HIGH,CRITICAL --format json . > head_vulnerabilities.json

    - name: Run Ruby script to compare vulnerabilities
      id: compare-vulnerabilities
      run: |
        ruby .github/scripts/compare_vulnerabilities.rb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get vulnerabilities for PR comment
      id: vulnerability-summary
      run: |
        ruby .github/scripts/compare_vulnerabilities.rb > summary.md
        cat summary.md
    
    - name: Post comment to GitHub PR with vulnerability summary
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const commentBody = fs.readFileSync('summary.md', 'utf-8');
          
          const { data } = await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: commentBody
          });
          console.log(data);
