name: Dependency Vulnerability Check

on:
  pull_request:
    paths:
      - '**/Gemfile.lock'
      - '**/package-lock.json'
      - '**/yarn.lock'
      - '**/pnpm-lock.yaml'

jobs:
  vulnerability-check:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1.3

    env:
      ALERT_ON: "MEDIUM,CRITICAL,HIGH" # Options: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add Git safe directory exception
        run: git config --global --add safe.directory /__w/testingscan/testingscan

      - name: Install Trivy
        run: |
          TRIVY_VERSION="0.59.1"
          REPOSITORY="aquasecurity/trivy"
          BASE_URL="https://github.com/${REPOSITORY}/releases/download/v${TRIVY_VERSION}"
          
          curl -L -o trivy.tar.gz "$BASE_URL/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz"
          curl -L -o trivy_checksums.txt "$BASE_URL/trivy_${TRIVY_VERSION}_checksums.txt"

          EXPECTED_CHECKSUM=$(grep "trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz" trivy_checksums.txt | awk '{print $1}')
          echo "$EXPECTED_CHECKSUM  trivy.tar.gz" | sha256sum -c -

          tar -xzf trivy.tar.gz -C /usr/local/bin
          trivy --version

      - name: Run Trivy on base commit
        id: trivy-base
        run: |
          git checkout origin/main
          trivy fs --quiet --scanners vuln --pkg-types library -s "$ALERT_ON" --format json . > base_vulnerabilities.json
          cat base_vulnerabilities.json

      - name: Run Trivy on head commit
        id: trivy-head
        run: |
          git checkout FETCH_HEAD
          trivy fs --quiet --scanners vuln --pkg-types library -s "$ALERT_ON" --format json . > head_vulnerabilities.json
          cat head_vulnerabilities.json

      - name: Run Ruby script to compare vulnerabilities
        id: compare-vulnerabilities
        run: |
          ruby .github/scripts/compare_vulnerabilities.rb
