name: Dependency Vulnerability Check

on:
  pull_request:
    paths:
      - '**/Gemfile.lock'
      - '**/package-lock.json'
      - '**/yarn.lock'
      - '**/pnpm-lock.yaml'

jobs:
  vulnerability-check:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git safe directory
      run: git config --global --add safe.directory /__w/testingscan/testingscan

    - name: Install Bundler
      run: gem install bundler

    - name: Run Trivy on base commit
      id: trivy-base
      run: |
        git checkout origin/main
        trivy fs --quiet --scanners vuln --pkg-types library -s HIGH,CRITICAL --format json . > base_vulnerabilities.json

    - name: Run Trivy on head commit
      id: trivy-head
      run: |
        git checkout FETCH_HEAD
        trivy fs --quiet --scanners vuln --pkg-types library -s HIGH,CRITICAL --format json . > head_vulnerabilities.json

    - name: Run Ruby script to compare vulnerabilities
      run: |
        ruby compare_vulnerabilities.rb
