name: Dependency Vulnerability Check

on:
  pull_request:
    paths:
      - '**/Gemfile.lock'
      - '**/package-lock.json'
      - '**/yarn.lock'
      - '**/pnpm-lock.yaml'

jobs:
  vulnerability-check:
    runs-on: ubuntu-latest
    container:
      image: ruby:latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add Git safe directory exception
        run: git config --global --add safe.directory /__w/testingscan/testingscan

      - name: Install Trivy
        run: |
          # Set version and URLs for the release binary and checksum file
          TRIVY_VERSION="0.59.1"
          REPOSITORY="aquasecurity/trivy"
          BASE_URL="https://github.com/${REPOSITORY}/releases/download/v${TRIVY_VERSION}"
          
          # Download the Trivy binary and the checksums file
          curl -L -o trivy.tar.gz $BASE_URL/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
          curl -L -o trivy_checksums.txt $BASE_URL/trivy_${TRIVY_VERSION}_checksums.txt

          # Extract the expected checksum for the Linux 64bit tar.gz file from the checksum file
          EXPECTED_CHECKSUM=$(grep "trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz" trivy_checksums.txt | awk '{print $1}')

          # Verify the checksum of the downloaded binary
          echo "$EXPECTED_CHECKSUM  trivy.tar.gz" | sha256sum -c -

          # Install Trivy from the downloaded binary if checksum is valid
          tar -xzf trivy.tar.gz -C /usr/local/bin
          trivy --version # Confirm installation

      - name: Run Trivy on base commit
        id: trivy-base
        run: |
          git checkout origin/main
          trivy fs --quiet --scanners vuln --pkg-types library -s HIGH,CRITICAL --format json . > base_vulnerabilities.json

      - name: Run Trivy on head commit
        id: trivy-head
        run: |
          git checkout FETCH_HEAD
          trivy fs --quiet --scanners vuln --pkg-types library -s HIGH,CRITICAL --format json . > head_vulnerabilities.json

      - name: Run Ruby script to compare vulnerabilities
        id: compare-vulnerabilities
        run: |
          ruby .github/scripts/compare_vulnerabilities.rb

