name: Dependency Vulnerability Check

on:
  pull_request:
    paths:
      - '**/Gemfile.lock'       # Ruby dependencies
      - '**/package-lock.json'  # Node.js dependencies
      - '**/yarn.lock'           # Alternative for Node.js
      - '**/pnpm-lock.yaml'      # pnpm dependencies

jobs:
  vulnerability-check:
    runs-on: ubuntu-latest
    steps:

    # Checkout the code (needed for accessing files)
    - name: Checkout the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure we fetch all branches

    # Install Trivy
    - name: Install Trivy
      run: |
        curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.59.1/trivy_0.59.1_Linux-64bit.tar.gz | tar -xz -C /usr/local/bin

    # Fetch the base commit and head commit (including the main branch)
    - name: Fetch base and head commits
      run: |
        # Fetch the main branch (default branch)
        git fetch origin main

        # Fetch the pull request branch (the merge commit for the PR)
        git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge

        # Checkout the base commit (main branch)
        git checkout origin/main

        # Now get the commit hash for the base commit (main) and the head commit (PR)
        BASE_COMMIT=$(git rev-parse origin/main)
        HEAD_COMMIT=$(git rev-parse FETCH_HEAD)

        echo "Base commit: $BASE_COMMIT"
        echo "Head commit: $HEAD_COMMIT"

        # Set the base and head commits as environment variables for later use
        echo "BASE_COMMIT=$BASE_COMMIT" >> $GITHUB_ENV
        echo "HEAD_COMMIT=$HEAD_COMMIT" >> $GITHUB_ENV

    # Run Trivy on the base commit
    - name: Run Trivy on base commit
      id: trivy-base
      run: |
        git checkout $BASE_COMMIT
        # Run Trivy on the entire repo for base commit
        trivy fs --quiet --scanners vuln --pkg-types library -s HIGH,CRITICAL --format json . > base_vulnerabilities.json

    # Run Trivy on the head commit
    - name: Run Trivy on head commit
      id: trivy-head
      run: |
        git checkout $HEAD_COMMIT
        # Run Trivy on the entire repo for head commit
        trivy fs --skip-update --quiet --severity HIGH,CRITICAL --format json . > head_vulnerabilities.json

    - name: Run Ruby script to compare vulnerabilities
      run: |
        ruby compare_vulnerabilities.rb
